package xiaozhi.common.utils;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

public class AESUtilsTest {

    @Test
    public void testEncryptAndDecrypt() {
        String key = "xiaozhi1234567890";
        String plainText = "Hello, Xiaozhi!";

        System.out.println("Original text:" + plainText);
        System.out.println("Key:" + key);

        // encryption
        String encrypted = AESUtils.encrypt(key, plainText);
        System.out.println("Encryption result:" + encrypted);

        // decrypt
        String decrypted = AESUtils.decrypt(key, encrypted);
        System.out.println("Decryption result:" + decrypted);

        // verify
        assertEquals(plainText, decrypted, "The encryption and decryption results should be consistent");
        System.out.println("Encryption and decryption consistency:" + plainText.equals(decrypted));
    }

    @Test
    public void testDifferentKeyLengths() {
        String[] keys = {
                "1234567890123456", // 16 bit
                "123456789012345678901234", // 24 bit
                "12345678901234567890123456789012", // 32 bit
                "short", // short_key
                "verylongkeythatwillbetruncatedto32bytes" // long_key
        };

        String plainText = "test text";

        for (String key : keys) {
            String encrypted = AESUtils.encrypt(key, plainText);
            String decrypted = AESUtils.decrypt(key, encrypted);
            assertEquals(plainText, decrypted, "Key length:" + key.length());
        }
    }

    @Test
    public void testSpecialCharacters() {
        String key = "xiaozhi1234567890";
        String[] testTexts = {
                "Hello World",
                "Hello World",
                "Hello, Xiaozhi!",
                "Special characters: !@#$%^&*()",
                "Number 123 mixed with Chinese",
                "Emoji: 😀🎉🚀",
                "empty string test",
                ""
        };

        for (String text : testTexts) {
            String encrypted = AESUtils.encrypt(key, text);
            String decrypted = AESUtils.decrypt(key, encrypted);
            assertEquals(text, decrypted, "Test text:" + text);
        }
    }

    @Test
    public void testCrossLanguageCompatibility() {
        // these_are_the_encryption_results_generated_by_the_python_version，for_testing_crosslanguage_compatibility
        String key = "xiaozhi1234567890";
        String plainText = "Hello, Xiaozhi!";

        // Encrypted results generated by Python version (need_to_get_after_running_python_test)
        // String pythonEncrypted = "Encrypted results obtained from Python test";from Python test";
        // String decrypted = AESUtils.decrypt(key, pythonEncrypted);
        // assertEquals(plainText, decrypted, "Java should be able to decrypt Python encrypted results");decrypt Python encrypted results");

        // generate_java_encryption_results_for_python_testing
        String javaEncrypted = AESUtils.encrypt(key, plainText);
        System.out.println("Java encryption results for Python testing:" + javaEncrypted);
    }
}